version: "3.8"

services:

  traefik:
    image: "traefik:latest"
    container_name: "roestbrueder_traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.email=info@datafortress.cloud"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  wordpress:
    image: wordpress
    container_name: "roestbrueder_wordpress"
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      #WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        # define( 'WP_DEBUG', true );
        # define('WP_CACHE', true);
        # define('WP_REDIS_HOST', 'redis');
        # define('WP_REDIS_PORT', '6379');
    volumes:
      - ./src/wordpress/data:/var/www/html/wp-content/
      - ./src/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      #- ./src/wordpress/wp-config.php:/var/www/html/wp-config.php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`roest-dev.datafortress.cloud`)"
      - "traefik.http.routers.wordpress.tls=true"
      #- "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=le"
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: 1.5

  db:
    image: mariadb:latest
    container_name: roestbrueder_mariadb
    volumes:
      - ./src/wordpress/sql:/var/lib/mysql
    restart: always
    environment:
      #MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    labels:
      - "traefik.enable=false"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: roestbrueder_phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      #PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8181:80
    labels:
      - "traefik.enable=false"

  # redis:
  #   image: redis:latest
  #   container_name: roestbrueder_redis
  #   restart: always
  #   # ports:
  #   #   - 6379:6379
  #   labels:
  #     - "traefik.enable=false"
  #   mem_limit: '500M'
